name: Build and Deploy Telegram Bot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore SampleGreeter/SampleGreeter.csproj

    - name: Build the app
      run: dotnet build SampleGreeter/SampleGreeter.csproj --configuration Release

    - name: Publish the app
      run: dotnet publish SampleGreeter/SampleGreeter.csproj -c Release -o publish

    - name: Copy published files to bot directory
      run: |
        robocopy publish C:\TelegramBot /MIR
        $rc = $LASTEXITCODE
        if ($rc -le 3) {
          exit 0
        } else {
          exit $rc
        }

    - name: Restart bot service
      run: |
        net start TelegramBotService
